### ISSUE TITLE
Aplicação não carrrega.

### ISSUE THREAD

**Issue by Rieidi** [Silva97/x86-visualizer#1]
Eu abri o site e eu digito e não aparece nada.
![image](https://github.com/Silva97/x86-visualizer/assets/128847349/8ba134d2-b90d-4fe1-afb5-2740f073479a)

**Comment by Silva97** [comment]
Olá, obrigado por abrir a _issue_ e reportar seu problema.

Você usa alguma extensão como NoScript para desabilitar o JavaScript das páginas? Pois JS é necessário para a ferramenta funcionar. Desabilitando o JS da página eu consegui simular o seu erro, mas com JS habilitado funciona normalmente.

Outra possibilidade seja algum adblock desabilitando o JS por algum motivo.

Se tiver certeza que o JS está rodando normalmente na página, poderia me dizer qual navegador você usa? E se possível verificar se há algum erro no console do navegador (e tirar um print), também ajudaria.

**Comment by Rieidi** [comment]
Opa, desculpa pela demora, eu não tenho ADBlocker nem extensões já tinha tentado usar outro navegador eu acho que é por que não tenho javascript no meu computador.

**Comment by Rieidi** [comment]
Eu tentei abrir um deles e da esse erro:
![image](https://github.com/Silva97/x86-visualizer/assets/128847349/7c66f787-3279-4a02-a04d-4c20930649ae)

**Comment by Silva97** [comment]
É que se você tentar abrir um script assim, o Windows vai executar como se fosse JScript usando o WSH. Você não precisa "instalar JavaScript", todo navegador moderno suporta JS sem precisar instalar nada. A engine do JS faz parte do navegador.

Tente abrir a aplicação por esse link: https://silva97.github.io/x86-visualizer/

Não é necessário fazer download do código para usá-la. E se não funcionar pelo link acima, pode ser alguma incompatibilidade com o seu navegador. Qual navegador você usa?

**Comment by Rieidi** [comment]
Obrigrado, funcionou pelo link. eu uso o OperaGx
Posso perguntar uma coisa sobre assembly / bits?

**Comment by Silva97** [comment]
Sim.

**Comment by Rieidi** [comment]
Estou desenvolvendo um compilador para Python e, embora ainda não tenha definido o método específico para a geração de código de máquina, suponhamos que eu obtenha sucesso nessa etapa. Nesse contexto, gostaria de entender como posso executar os bits de código gerados. Uma abordagem viável seria a injeção direta no processador?

**Comment by Silva97** [comment]
Você pode gerar um executável, assim como compiladores convencionais normalmente fazem. Para isso estude sobre o formato de executável do sistema operacional (ELF no Linux e PE no Windows).

Ou então, se for seu intuito, você pode escrever um compilador JIT (pesquise à respeito caso não já esteja familiarizado com o conceito).

Entenda que não existe "injetar código no processador". Código de máquina fica na memória principal (RAM) e não "injetado" no processador.

Para entender como um processador funciona e como ele executa código, sugiro assistir essa apresentação que eu fiz. Ela tem 2 horas de duração mas, creio, vai te ajudar bastante: https://www.youtube.com/live/E7TEz60UA90?si=t-EQ_nw5paNu3kJN

Também tem esse livro de Assembly que eu escrevi. Tem um capítulo que explica o código de máquina da arquitetura x86-64. Pode lhe ser útil também: https://mentebinaria.gitbook.io/assembly/

**Comment by Rieidi** [comment]
Oh obrigado, eu estou fazendo um compilador jit então ele vai escrever na memoria eu consigo escrever bits na memoria?

**Comment by Silva97** [comment]
Tudo na memória são bits, então sim, consegue. E a ideia é essa mesma: você escreve o código na memória e executa ele lá.

**Comment by Rieidi** [comment]
Tudo bem, vou ver o livro e a aula valeu.
